// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ME_SaveSystemCore","status":true,"description":"My custom save plugin","parameters":{"maxSaves":"20","salt":"asd123.A@b","hash":"true"}}
];
